/* This file is generated by scripts/build-registry-data.mjs. */
export const registry = {
  "products": [
    {
      "slug": "agentforce-revenue-management-formerly-salesforce-revenue-cloud",
      "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/index.md",
      "title": "Agentforce Revenue Management (formerly Salesforce Revenue Cloud)",
      "description": "Initial seed for Agentforce Revenue Management (formerly Salesforce Revenue Cloud) in Subscription Billing.",
      "vendorId": "salesforce",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "adjacent",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/reviews",
      "rank": 7,
      "rating": "4.2/5",
      "reviewCount": 1497,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Agentforce Revenue Management, formerly Salesforce Revenue Cloud, is positioned around CPQ, pricing, quoting, billing, and revenue operations in the Salesforce ecosystem.",
      "buyerFit": "Best modeled as adjacent to Subscription Billing: strong for Salesforce-centered revenue management and CPQ workflows, with billing relevance inside a broader revenue operations suite.",
      "strengths": [
        "ease of use",
        "revenue management",
        "efficiency",
        "product functionality",
        "features"
      ],
      "cautions": [
        "learning curve",
        "complexity",
        "complex setup",
        "beginner difficulty",
        "customization expertise"
      ],
      "features": [],
      "pricingSignal": "Not shown in category listing",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "chargebee",
      "path": "software/products/chargebee/index.md",
      "title": "Chargebee",
      "description": "Initial seed for Chargebee in Subscription Billing.",
      "vendorId": "chargebee",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "core",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/chargebee/reviews",
      "rank": 1,
      "rating": "4.4/5",
      "reviewCount": 961,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Chargebee is a subscription billing and monetization platform focused on recurring revenue, pricing flexibility, subscription operations, and revenue scale.",
      "buyerFit": "Best modeled as a core Subscription Billing product, especially for software and technology companies that need subscription management, billing automation, pricing-packaging flexibility, and revenue operations workflows.",
      "strengths": [
        "ease of use",
        "subscription management",
        "customer support",
        "billing management",
        "integrations"
      ],
      "cautions": [
        "limited customization",
        "support variability",
        "access limitations",
        "cost concerns",
        "missing features"
      ],
      "features": [],
      "pricingSignal": "Free",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/chargebee/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/chargebee/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/chargebee/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/chargebee/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/chargebee/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/chargebee/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/chargebee/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/chargebee/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/chargebee/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/chargebee/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "maxio",
      "path": "software/products/maxio/index.md",
      "title": "Maxio",
      "description": "Initial seed for Maxio in Subscription Billing.",
      "vendorId": "maxio",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "core",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/maxio/reviews",
      "rank": 4,
      "rating": "4.3/5",
      "reviewCount": 829,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Maxio is a B2B SaaS financial operations platform covering billing, subscription management, accounts receivable, revenue recognition, and revenue operations workflows.",
      "buyerFit": "Best modeled as a core Subscription Billing product for B2B SaaS companies that need subscription billing connected to financial operations and revenue recognition.",
      "strengths": [
        "accounts receivable",
        "API flexibility",
        "subscription management",
        "revenue recognition",
        "billing management"
      ],
      "cautions": [
        "reporting gaps",
        "integration issues",
        "missing features",
        "invoicing issues",
        "add-on complexity"
      ],
      "features": [],
      "pricingSignal": "Free trial available",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/maxio/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/maxio/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/maxio/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/maxio/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/maxio/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/maxio/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/maxio/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/maxio/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/maxio/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/maxio/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "netsuite",
      "path": "software/products/netsuite/index.md",
      "title": "NetSuite",
      "description": "Initial seed for NetSuite in Subscription Billing.",
      "vendorId": "oracle",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "adjacent",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/netsuite/reviews",
      "rank": 2,
      "rating": "4.1/5",
      "reviewCount": 4677,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "NetSuite is a broad cloud ERP and financial management platform. In this category, its relevance appears tied to finance, billing, and operational accounting workflows rather than pure-play subscription billing.",
      "buyerFit": "Best modeled as adjacent to Subscription Billing: useful for buyers who want subscription billing inside a broader ERP and finance system, less direct for buyers seeking a standalone subscription billing product.",
      "strengths": [
        "ease of use",
        "customizability",
        "functionality",
        "customization options",
        "reporting capabilities"
      ],
      "cautions": [
        "learning curve",
        "missing features",
        "limited customization",
        "not user-friendly",
        "unclear error handling"
      ],
      "features": [],
      "pricingSignal": "Not shown in category listing",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/netsuite/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/netsuite/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/netsuite/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/netsuite/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/netsuite/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/netsuite/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/netsuite/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/netsuite/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/netsuite/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/netsuite/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "paddle",
      "path": "software/products/paddle/index.md",
      "title": "Paddle",
      "description": "Initial seed for Paddle in Subscription Billing.",
      "vendorId": "paddle",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "core",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/paddle/reviews",
      "rank": 5,
      "rating": "4.5/5",
      "reviewCount": 236,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Paddle is a subscription billing and merchant-of-record platform for digital businesses, combining payments, tax, compliance, billing, and reporting workflows.",
      "buyerFit": "Best modeled as a core Subscription Billing product for SaaS, AI, app, game, and digital-product companies that want subscription billing packaged with merchant-of-record responsibilities.",
      "strengths": [
        "customer support",
        "ease of use",
        "payment processing",
        "helpfulness",
        "payment management"
      ],
      "cautions": [
        "improvement needed",
        "support variability",
        "access limitations",
        "billing issues",
        "limited data visibility"
      ],
      "features": [],
      "pricingSignal": "Pay As You Go",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/paddle/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/paddle/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/paddle/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/paddle/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/paddle/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/paddle/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/paddle/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/paddle/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/paddle/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/paddle/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "paypal-invoicing",
      "path": "software/products/paypal-invoicing/index.md",
      "title": "PayPal Invoicing",
      "description": "Initial seed for PayPal Invoicing in Subscription Billing.",
      "vendorId": "paypal",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "partial",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/paypal-invoicing/reviews",
      "rank": 6,
      "rating": "4.4/5",
      "reviewCount": 175,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "PayPal Invoicing is an invoicing product for creating, sending, tracking, and managing professional invoices through the PayPal ecosystem.",
      "buyerFit": "Best modeled as a partial Subscription Billing fit: useful for invoicing and payment collection, but the initial category-page evidence does not establish full subscription billing depth.",
      "strengths": [
        "ease of use",
        "invoicing",
        "invoice management",
        "speed",
        "payment processing"
      ],
      "cautions": [
        "expense concerns",
        "high fees",
        "limited customization",
        "payment issues",
        "invoicing issues"
      ],
      "features": [],
      "pricingSignal": "Pay As You Go",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/paypal-invoicing/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/paypal-invoicing/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/paypal-invoicing/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/paypal-invoicing/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/paypal-invoicing/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/paypal-invoicing/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/paypal-invoicing/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/paypal-invoicing/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/paypal-invoicing/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/paypal-invoicing/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "sage-intacct",
      "path": "software/products/sage-intacct/index.md",
      "title": "Sage Intacct",
      "description": "Initial seed for Sage Intacct in Subscription Billing.",
      "vendorId": "sage-software",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "adjacent",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/sage-intacct/reviews",
      "rank": 3,
      "rating": "4.3/5",
      "reviewCount": 4118,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Sage Intacct is a cloud financial platform with deep accounting capabilities. In Subscription Billing, its relevance is tied to accounting, finance, and recurring revenue management workflows.",
      "buyerFit": "Best modeled as adjacent to Subscription Billing: strong for finance teams that need billing context within accounting, but not necessarily a pure subscription billing system.",
      "strengths": [
        "ease of use",
        "intuitive interface",
        "reporting",
        "user-friendly workflows",
        "feature depth"
      ],
      "cautions": [
        "missing features",
        "learning curve",
        "limited functionality",
        "access limitations",
        "new-user complexity"
      ],
      "features": [],
      "pricingSignal": "Not shown in category listing",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/sage-intacct/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/sage-intacct/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/sage-intacct/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/sage-intacct/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/sage-intacct/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/sage-intacct/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/sage-intacct/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/sage-intacct/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/sage-intacct/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/sage-intacct/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "square-point-of-sale",
      "path": "software/products/square-point-of-sale/index.md",
      "title": "Square Point of Sale",
      "description": "Initial seed for Square Point of Sale in Subscription Billing.",
      "vendorId": "block",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "partial",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/square-point-of-sale/reviews",
      "rank": 10,
      "rating": "4.6/5",
      "reviewCount": 1196,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Square Point of Sale is a point-of-sale and payments product for retail, restaurants, services, and other small-business contexts. In Subscription Billing, its fit appears limited to payment and recurring/customer-management adjacency.",
      "buyerFit": "Best modeled as a partial Subscription Billing fit: useful for buyers whose billing need is tightly tied to POS and payments, but not a pure subscription billing platform based on this seed.",
      "strengths": [
        "ease of use",
        "payment processing",
        "features",
        "simplicity",
        "setup ease"
      ],
      "cautions": [
        "high fees",
        "expense concerns",
        "access limitations",
        "missing features",
        "payment issues"
      ],
      "features": [],
      "pricingSignal": "Free",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/square-point-of-sale/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/square-point-of-sale/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/square-point-of-sale/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/square-point-of-sale/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/square-point-of-sale/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/square-point-of-sale/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/square-point-of-sale/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/square-point-of-sale/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/square-point-of-sale/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/square-point-of-sale/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "stripe-billing",
      "path": "software/products/stripe-billing/index.md",
      "title": "Stripe Billing",
      "description": "Initial seed for Stripe Billing in Subscription Billing.",
      "vendorId": "stripe",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "core",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/stripe-billing/reviews",
      "rank": 8,
      "rating": "4.4/5",
      "reviewCount": 139,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Stripe Billing is a recurring billing product for billing customers, supporting recurring payments, monetization models, and recovery workflows within the Stripe payments ecosystem.",
      "buyerFit": "Best modeled as a core Subscription Billing product for companies already using or considering Stripe for payments and recurring revenue workflows.",
      "strengths": [
        "payment processing",
        "subscription management",
        "easy integrations",
        "integrations",
        "ease of use"
      ],
      "cautions": [
        "expense concerns",
        "pricing issues",
        "access limitations",
        "complex pricing",
        "high fees"
      ],
      "features": [],
      "pricingSignal": "2.9% + 30c per successful charge, as displayed in the category listing",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/stripe-billing/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/stripe-billing/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/stripe-billing/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/stripe-billing/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/stripe-billing/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/stripe-billing/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/stripe-billing/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/stripe-billing/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/stripe-billing/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/stripe-billing/vendor-claims.md"
        }
      ]
    },
    {
      "slug": "zoho-billing",
      "path": "software/products/zoho-billing/index.md",
      "title": "Zoho Billing",
      "description": "Initial seed for Zoho Billing in Subscription Billing.",
      "vendorId": "zoho",
      "displayCategory": "subscription-billing",
      "categoryMemberships": [
        {
          "category_id": "subscription-billing",
          "fit": "core",
          "source_tier": "public-cited",
          "reviewed_at": "2026-06-29"
        }
      ],
      "sourceTier": "public-cited",
      "owner": "g2",
      "claimPolicy": "none",
      "resource": "https://www.g2.com/products/zoho-billing/reviews",
      "rank": 9,
      "rating": "4.4/5",
      "reviewCount": 45,
      "observedAt": "2026-06-29",
      "expiresAt": "2027-06-29",
      "profile": "Zoho Billing is a billing and invoicing solution for growing businesses, oriented around billing workflow simplification and business scaling.",
      "buyerFit": "Best modeled as a core Subscription Billing product for small and mid-sized businesses that want billing and invoicing inside the Zoho ecosystem.",
      "strengths": [
        "analytics",
        "easy integrations",
        "integrations",
        "affordability",
        "app variety"
      ],
      "cautions": [
        "access limitations",
        "expense concerns",
        "subscription cost concerns",
        "implementation issues",
        "inefficiency"
      ],
      "features": [],
      "pricingSignal": "$25.00",
      "files": [
        {
          "name": "alternatives.md",
          "path": "software/products/zoho-billing/alternatives.md"
        },
        {
          "name": "features.md",
          "path": "software/products/zoho-billing/features.md"
        },
        {
          "name": "index.md",
          "path": "software/products/zoho-billing/index.md"
        },
        {
          "name": "integrations.md",
          "path": "software/products/zoho-billing/integrations.md"
        },
        {
          "name": "log.md",
          "path": "software/products/zoho-billing/log.md"
        },
        {
          "name": "pricing.md",
          "path": "software/products/zoho-billing/pricing.md"
        },
        {
          "name": "profile.md",
          "path": "software/products/zoho-billing/profile.md"
        },
        {
          "name": "reviews-summary.md",
          "path": "software/products/zoho-billing/reviews-summary.md"
        },
        {
          "name": "security-compliance.md",
          "path": "software/products/zoho-billing/security-compliance.md"
        },
        {
          "name": "vendor-claims.md",
          "path": "software/products/zoho-billing/vendor-claims.md"
        }
      ]
    }
  ],
  "categories": [
    {
      "slug": "crm",
      "path": "software/categories/crm/index.md",
      "title": "CRM",
      "description": "Customer relationship management software category.",
      "sourceTier": "g2-curated",
      "parents": [
        "sales-software"
      ],
      "children": [
        "enterprise-crm",
        "small-business-crm"
      ],
      "relatedCategories": [
        "sales-engagement",
        "customer-success",
        "marketing-automation"
      ],
      "status": "active",
      "resource": "",
      "reviewedAt": "",
      "expiresAt": "",
      "productRows": []
    },
    {
      "slug": "subscription-billing",
      "path": "software/categories/subscription-billing/index.md",
      "title": "Subscription Billing",
      "description": "Subscription billing software category seeded from the public G2 category page.",
      "sourceTier": "public-cited",
      "parents": [
        "billing"
      ],
      "children": [],
      "relatedCategories": [
        "subscription-management",
        "subscription-revenue-management",
        "revenue-recognition",
        "payment-processing",
        "merchant-of-record",
        "invoicing"
      ],
      "status": "active",
      "resource": "https://www.g2.com/categories/subscription-billing",
      "reviewedAt": "2026-06-29",
      "expiresAt": "2026-09-27",
      "productRows": [
        {
          "rank": "1",
          "product": "[Chargebee](../../products/chargebee/index.md)",
          "vendor": "[Chargebee](../../vendors/chargebee/index.md)",
          "fit": "core",
          "rating": "4.4/5",
          "reviewCount": "961",
          "segment": "72% Small-Business, 22% Mid-Market"
        },
        {
          "rank": "2",
          "product": "[NetSuite](../../products/netsuite/index.md)",
          "vendor": "[Oracle](../../vendors/oracle/index.md)",
          "fit": "adjacent",
          "rating": "4.1/5",
          "reviewCount": "4677",
          "segment": "57% Mid-Market, 31% Small-Business"
        },
        {
          "rank": "3",
          "product": "[Sage Intacct](../../products/sage-intacct/index.md)",
          "vendor": "[Sage Software](../../vendors/sage-software/index.md)",
          "fit": "adjacent",
          "rating": "4.3/5",
          "reviewCount": "4118",
          "segment": "58% Mid-Market, 25% Small-Business"
        },
        {
          "rank": "4",
          "product": "[Maxio](../../products/maxio/index.md)",
          "vendor": "[Maxio](../../vendors/maxio/index.md)",
          "fit": "core",
          "rating": "4.3/5",
          "reviewCount": "829",
          "segment": "53% Small-Business, 44% Mid-Market"
        },
        {
          "rank": "5",
          "product": "[Paddle](../../products/paddle/index.md)",
          "vendor": "[Paddle](../../vendors/paddle/index.md)",
          "fit": "core",
          "rating": "4.5/5",
          "reviewCount": "236",
          "segment": "89% Small-Business, 8% Mid-Market"
        },
        {
          "rank": "6",
          "product": "[PayPal Invoicing](../../products/paypal-invoicing/index.md)",
          "vendor": "[PayPal](../../vendors/paypal/index.md)",
          "fit": "partial",
          "rating": "4.4/5",
          "reviewCount": "175",
          "segment": "67% Small-Business, 25% Mid-Market"
        },
        {
          "rank": "7",
          "product": "[Agentforce Revenue Management (formerly Salesforce Revenue Cloud)](../../products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/index.md)",
          "vendor": "[Salesforce](../../vendors/salesforce/index.md)",
          "fit": "adjacent",
          "rating": "4.2/5",
          "reviewCount": "1497",
          "segment": "45% Mid-Market, 33% Enterprise"
        },
        {
          "rank": "8",
          "product": "[Stripe Billing](../../products/stripe-billing/index.md)",
          "vendor": "[Stripe](../../vendors/stripe/index.md)",
          "fit": "core",
          "rating": "4.4/5",
          "reviewCount": "139",
          "segment": "78% Small-Business, 18% Mid-Market"
        },
        {
          "rank": "9",
          "product": "[Zoho Billing](../../products/zoho-billing/index.md)",
          "vendor": "[Zoho](../../vendors/zoho/index.md)",
          "fit": "core",
          "rating": "4.4/5",
          "reviewCount": "45",
          "segment": "71% Small-Business, 18% Mid-Market"
        },
        {
          "rank": "10",
          "product": "[Square Point of Sale](../../products/square-point-of-sale/index.md)",
          "vendor": "[Block](../../vendors/block/index.md)",
          "fit": "partial",
          "rating": "4.6/5",
          "reviewCount": "1196",
          "segment": "89% Small-Business, 7% Mid-Market"
        }
      ]
    }
  ],
  "vendors": [
    {
      "slug": "block",
      "path": "software/vendors/block/index.md",
      "title": "Block",
      "description": "Vendor seed for Block.",
      "sourceTier": "public-cited",
      "resource": "https://block.xyz/",
      "products": [
        {
          "product": "[Square Point of Sale](../../products/square-point-of-sale/index.md)",
          "category": "Subscription Billing",
          "fit": "partial"
        }
      ]
    },
    {
      "slug": "chargebee",
      "path": "software/vendors/chargebee/index.md",
      "title": "Chargebee",
      "description": "Vendor seed for Chargebee.",
      "sourceTier": "public-cited",
      "resource": "https://www.chargebee.com/",
      "products": [
        {
          "product": "[Chargebee](../../products/chargebee/index.md)",
          "category": "Subscription Billing",
          "fit": "core"
        }
      ]
    },
    {
      "slug": "maxio",
      "path": "software/vendors/maxio/index.md",
      "title": "Maxio",
      "description": "Vendor seed for Maxio.",
      "sourceTier": "public-cited",
      "resource": "https://www.maxio.com/",
      "products": [
        {
          "product": "[Maxio](../../products/maxio/index.md)",
          "category": "Subscription Billing",
          "fit": "core"
        }
      ]
    },
    {
      "slug": "oracle",
      "path": "software/vendors/oracle/index.md",
      "title": "Oracle",
      "description": "Vendor seed for Oracle.",
      "sourceTier": "public-cited",
      "resource": "https://www.oracle.com/",
      "products": [
        {
          "product": "[NetSuite](../../products/netsuite/index.md)",
          "category": "Subscription Billing",
          "fit": "adjacent"
        }
      ]
    },
    {
      "slug": "paddle",
      "path": "software/vendors/paddle/index.md",
      "title": "Paddle",
      "description": "Vendor seed for Paddle.",
      "sourceTier": "public-cited",
      "resource": "https://paddle.com",
      "products": [
        {
          "product": "[Paddle](../../products/paddle/index.md)",
          "category": "Subscription Billing",
          "fit": "core"
        }
      ]
    },
    {
      "slug": "paypal",
      "path": "software/vendors/paypal/index.md",
      "title": "PayPal",
      "description": "Vendor seed for PayPal.",
      "sourceTier": "public-cited",
      "resource": "https://www.paypal.com/",
      "products": [
        {
          "product": "[PayPal Invoicing](../../products/paypal-invoicing/index.md)",
          "category": "Subscription Billing",
          "fit": "partial"
        }
      ]
    },
    {
      "slug": "sage-software",
      "path": "software/vendors/sage-software/index.md",
      "title": "Sage Software",
      "description": "Vendor seed for Sage Software.",
      "sourceTier": "public-cited",
      "resource": "https://www.sage.com/",
      "products": [
        {
          "product": "[Sage Intacct](../../products/sage-intacct/index.md)",
          "category": "Subscription Billing",
          "fit": "adjacent"
        }
      ]
    },
    {
      "slug": "salesforce",
      "path": "software/vendors/salesforce/index.md",
      "title": "Salesforce",
      "description": "Vendor seed for Salesforce.",
      "sourceTier": "public-cited",
      "resource": "https://www.salesforce.com/",
      "products": [
        {
          "product": "[Agentforce Revenue Management (formerly Salesforce Revenue Cloud)](../../products/agentforce-revenue-management-formerly-salesforce-revenue-cloud/index.md)",
          "category": "Subscription Billing",
          "fit": "adjacent"
        }
      ]
    },
    {
      "slug": "stripe",
      "path": "software/vendors/stripe/index.md",
      "title": "Stripe",
      "description": "Vendor seed for Stripe.",
      "sourceTier": "public-cited",
      "resource": "https://stripe.com",
      "products": [
        {
          "product": "[Stripe Billing](../../products/stripe-billing/index.md)",
          "category": "Subscription Billing",
          "fit": "core"
        }
      ]
    },
    {
      "slug": "zoho",
      "path": "software/vendors/zoho/index.md",
      "title": "Zoho",
      "description": "Vendor seed for Zoho.",
      "sourceTier": "public-cited",
      "resource": "https://www.zoho.com",
      "products": [
        {
          "product": "[Zoho Billing](../../products/zoho-billing/index.md)",
          "category": "Subscription Billing",
          "fit": "core"
        }
      ]
    }
  ],
  "stats": {
    "products": 10,
    "categories": 2,
    "vendors": 10,
    "files": 100
  }
} as const
